-- Song import from 'Sunday Scheduling for Music Team.xlsx' (2026-07-05).
-- default_key = female key from the sheet; male_key alongside; artists best-effort.
insert into songs (title, artist, default_key, male_key, tempo_bpm, time_signature, notes, tags) values
('A Thousand Hallelujahs','Brooke Ligertwood','Db',null,68,'4/4',null,null),
('A Thousand Names',null,'D','G',64,'4/4',null,null),
('All about you',null,'D','A',98,'4/4',null,null),
('All hail king Jesus','Jeremy Riddle','A','C',68,'4/4',null,null),
('All my thank yous',null,'D or Db','G',null,null,null,null),
('Always so good',null,'E','C (B poss)',73,'4/4',null,null),
('Amazing Grace (My Chains are Gone)','Chris Tomlin','F','G',74,'4/4',null,null),
('Another In The Fire','Hillsong UNITED','G','C',67,'4/4',null,null),
('Awake My Soul','Hillsong Worship','F','G',63,'4/4',null,null),
('Beautiful Day',null,'G','C',139,'4/4',null,null),
('Because of Jesus',null,'G','C (DA)',67,'4/4',null,null),
('Bless God','Brooke Ligertwood','D','A',72,'4/4',null,null),
('Breakthrough Here',null,'G','A',74,'4/4',null,null),
('Breathe',null,'E',null,58,'4/4',null,null),
('Build my life','Pat Barrett','D','G',70,'4/4',null,null),
('Can''t help but worship',null,'F','A',127,'4/4',null,null),
('Come to the altar','Elevation Worship','C','A',140,'6/8',null,null),
('Cornerstone','Hillsong Worship',null,'C',71,'4/4',null,null),
('Crowns down',null,'F','A',74,'4/4',null,null),
('Deep down',null,'G','D',120,'4/4',null,null),
('Deeper water',null,'G','C',102,'4/4',null,null),
('Echo','Elevation Worship','F','A',72,'4/4',null,null),
('Echoes (Till we see the other side)',null,'E','A/ G?',142,'4/4',null,null),
('Everything and nothing less',null,'F','D',104,'4/4',null,null),
('Faithful Now','Vertical Worship','E',null,74,'4/4',null,null),
('Faithful then, faithful now',null,'D','G',107,'4/4',null,null),
('Fall like rain',null,'F','A',72,'4/4',null,null),
('Finished work',null,null,null,null,null,null,null),
('Firm Foundation','Cody Carnes','C','G',75,'3/8',null,null),
('Freedom (Hillsong)','Hillsong UNITED','E','A/ G?',75,'4/4',null,null),
('Freedom (Jesus Culture)','Jesus Culture','G','C',124,'4/4',null,null),
('Freedom is coming',null,'G','D',94,'4/4',null,null),
('Fullness',null,'E/F','A',70,'4/4',null,null),
('Give me Jesus','UPPERROOM','E','G / C(DA)',70,'4/4','Check Male key when picking',null),
('Glorious Day','Passion','F','C',72,'4/4',null,null),
('God So Loved','We The Kingdom','Bb','G',100,'4/4',null,null),
('Good Good Father','Chris Tomlin','F','G',74,'6/8',null,null),
('Good Grace','Hillsong UNITED','A','C/ D',110,'4/4',null,null),
('Goodbye yesterday',null,'F','G',71,'4/4',null,null),
('Goodness of God','Bethel Music','F/G','A',63,'4/4','G female is more comfortable',null),
('Gratitude','Brandon Lake','F','A',52,'6/8',null,null),
('Graves into Gardens','Elevation Worship','B','A',70,'3/8',null,null),
('Here Again','Elevation Worship','A','D',75,'4/4',null,null),
('Highest one',null,'G','A',70,'4/4',null,null),
('Highest praise (we get low)',null,'E','G',72,'4/4',null,null),
('Holy are you Lord',null,'any- bridge song','C',68,'4/4',null,null),
('Holy forever','Chris Tomlin','F','C',68,'4/4',null,null),
('Holy Spirit you are welcome here','Bryan & Katie Torwalt','D',null,72,'4/4',null,null),
('House of Miracles','Brandon Lake','E','A',72,'4/4',null,null),
('House of the Lord','Phil Wickham','D','A',86,'4/4',null,null),
('How He loves','John Mark McMillan','F','C',49,'6/8',null,null),
('I know a name',null,'E','A',58,'6/8',null,null),
('I Speak Jesus','Charity Gayle','E','C',74,'4/4',null,null),
('I surrender all (BNL version)','Breathe New Life','D','D',74,'4/4',null,null),
('I Thank God','Maverick City Music','F','B',72,'4/4',null,null),
('In Jesus'' Name (God of Possible)','Katy Nichole','F','A',130,'4/4',null,null),
('Jehovah','Elevation Worship','Eb','A',100,'4/4',null,null),
('Jesus over everything',null,'D','G',74,'4/4',null,null),
('Joy (what the world calls foolish)',null,'F','A',71,'4/4',null,null),
('King of Kings','Hillsong Worship','D','F',68,'4/4',null,null),
('King of my heart','John Mark & Sarah McMillan','F','C',124,'4/4',null,null),
('Left it in the river',null,'Ab','B?',98,'4/4',null,null),
('Light Up',null,'F','Bb',75,'4/4',null,null),
('Lion and the Lamb','Leeland','F','A',90,'4/4',null,null),
('Living hope','Phil Wickham','G','D',72,'4/4',null,null),
('Look how he lifted me',null,'B?',null,114,'4/4',null,null),
('Made for more',null,'E','C',75,'3/8',null,null),
('Make room',null,'F','C',62,'4/4',null,null),
('Mercy','Elevation Worship & Maverick City','E','G',65,'4/4',null,null),
('Mighty Cross',null,'G','D',72,'4/4',null,null),
('Mighty name of Jesus',null,'F or Eb','A',72,'4/4',null,null),
('Miracle in me',null,null,null,79,'4/4',null,null),
('Move',null,'E','C',120,'4/4',null,null),
('My King forever',null,'E','D (A- Dave)',72,'6/8',null,null),
('Name above all names',null,'D','G',75,'4/4',null,null),
('New thing coming',null,'Eb','A',91,'4/4',null,null),
('New Wine','Hillsong Worship','D','G',77,'4/4',null,null),
('No body',null,'E','C',67,'4/4',null,null),
('No longer slaves','Bethel Music','Bb','F',74,'4/4',null,null),
('No one (Yahweh)',null,'E','G',136,'4/4',null,null),
('None like you',null,'G','C',76,'6/8',null,null),
('O Praise the Name (Anástasis)','Hillsong Worship','G','C',72,'4/4',null,null),
('Oceans','Hillsong UNITED','G','D',65,'4/4',null,null),
('Only ever good',null,'E','A',82,'4/4',null,null),
('Pour your spirit out',null,'E/F','A',70,'4/4',null,null),
('Praise God (Doxology)',null,'E','A/B',126,'4/4',null,null),
('Praise!','Elevation Worship','D','E',127,'4/4',null,null),
('Raise a hallelujah','Bethel Music','Db','G',82,'4/4',null,null),
('RATTLE!','Elevation Worship','G','Eb?',76,'4/4',null,null),
('Reckless Love','Cory Asbury','C','F',56,'6/8',null,null),
('Resurrecting','Elevation Worship',null,'Ab',74,'4/4',null,null),
('Same God','Elevation Worship','G','C',72,'4/4',null,null),
('See A Victory','Elevation Worship','F/G','A',77,'4/4',null,null),
('See the Light',null,'F','A',116,'4/4',null,null),
('Shine for you',null,'E','G',118,'4/4',null,null),
('Simple Kingdom',null,'G','C',190,'6/8',null,null),
('Something has to break',null,null,null,null,null,null,null),
('So so good',null,'F','C',null,null,null,null),
('Stand in Your Love','Josh Baldwin','C/ G','G',72,'4/4',null,null),
('Surrounded (Fight My Battles)','UPPERROOM','G','Bb',70,'4/4',null,null),
('Take Courage','Kristene DiMarco','G',null,71,'4/4',null,null),
('Take You at Your Word','Cody Carnes','G','C',115,'4/4',null,null),
('That''s my king','CeCe Winans','A','D',95,'4/4',null,null),
('That''s the Power','Hillsong Worship','Eb','Bb (A Dave)',73,'4/4',null,null),
('That''s who I praise',null,'A','D',112,'4/4',null,null),
('The Blessing','Kari Jobe & Cody Carnes','B','G',70,'4/4',null,null),
('The Church will Rise',null,'D','A',77,'4/4',null,null),
('The In-between',null,'F','A',74,'4/4',null,null),
('The King is in the room',null,'Bb','G',null,null,null,null),
('The Way (New Horizon)','Pat Barrett','Eb','Bb',80,'4/4',null,null),
('There is a cloud',null,'G','D',68,'6/8',null,null),
('This is our God','Phil Wickham','G','C',80,'4/4',null,null),
('This is the kingdom',null,'E','A',49,'6/8',null,null),
('Tremble','Mosaic MSC','C','F',74,'4/4',null,null),
('Waiting here for you','Christy Nockels','C','A',66,'4/4',null,null),
('Way Maker','Sinach','B','G (DA - D)',68,'4/4',null,null),
('We believe','Newsboys','F','C',66,'4/4',null,null),
('Weapon',null,'E','B',73,'4/4',null,null),
('What a Beautiful Name','Hillsong Worship','D',null,68,'4/4',null,null),
('What He''s done','Passion','D/Db','A',71,'4/4',null,null),
('What I See',null,'E','A/C',148,'4/4',null,null),
('Who else?',null,'F/G','C',68,'4/4',null,null),
('Who You Say I Am','Hillsong Worship','G','C',58,'6/8',null,null),
('Wind of your spirit',null,'E','A',66,'4/4',null,null),
('Won''t Stop Now','Elevation Worship','D','G',122,'4/4',null,null),
('Words we''ll sing forever',null,'F','A',73,'4/4','check female key- G?',null),
('World Outside Your Window',null,'G','A',137,'4/4',null,null),
('Worship!',null,'C','D',130,'4/4',null,null),
('Worthy of it all','UPPERROOM','E',null,69,'4/4',null,null),
('Yahweh (Thrive worship)',null,'E','G',76,'6/8',null,null),
('Yes and Amen','Housefires','A','D',122,'4/4',null,null),
('Yes I Will',null,'G','A',75,'4/4',null,null),
('You Say','Lauren Daigle','F',null,74,'4/4',null,null),
('10000 Reasons','Matt Redman',null,null,73,'4/4',null,array['rarely used']::text[]),
('Available',null,null,null,80,'4/4',null,array['rarely used']::text[]),
('Build your kingdom here','Rend Collective','A','D',137,'4/4',null,array['rarely used']::text[]),
('Do it again','Elevation Worship',null,'Bb',86,'4/4',null,array['rarely used']::text[]),
('Fall',null,null,null,null,null,null,array['rarely used']::text[]),
('Give thanks to God',null,null,null,null,null,null,array['rarely used']::text[]),
('Gone',null,'D','G',null,null,null,array['rarely used']::text[]),
('Great Things (Worth it all)',null,null,null,null,null,null,array['rarely used']::text[]),
('Heal our Land',null,null,null,null,null,null,array['rarely used']::text[]),
('Here I am Send Me',null,null,null,null,null,null,array['rarely used']::text[]),
('Hindsight',null,null,null,null,null,null,array['rarely used']::text[]),
('I Will Boast',null,null,null,null,null,null,array['rarely used']::text[]),
('In the River',null,null,null,null,null,null,array['rarely used']::text[]),
('Joy of the Lord',null,null,null,null,null,null,array['rarely used']::text[]),
('Kingdom Come (LC)',null,null,null,null,null,null,array['rarely used']::text[]),
('Love overcomes',null,null,null,null,null,null,array['rarely used']::text[]),
('Make Us One',null,null,null,null,null,null,array['rarely used']::text[]),
('Man of Sorrows','Hillsong Worship',null,null,null,null,null,array['rarely used']::text[]),
('Miracles Happen',null,null,null,null,null,null,array['rarely used']::text[]),
('Nailed to the cross','Rend Collective',null,null,null,null,null,array['rarely used']::text[]),
('Never Let Me Go',null,null,null,null,null,null,array['rarely used']::text[]),
('Open Heaven (River Wild)','Hillsong Worship',null,'G',null,null,null,array['rarely used']::text[]),
('Overcome',null,null,null,null,null,null,array['rarely used']::text[]),
('Peace be still',null,null,null,null,null,null,array['rarely used']::text[]),
('Real love',null,null,null,null,null,null,array['rarely used']::text[]),
('Resurrection Day',null,null,null,null,null,null,array['rarely used']::text[]),
('So Will I (100 Billion X) (ST)','Hillsong UNITED',null,null,null,null,null,array['rarely used']::text[]),
('Stand Up',null,null,null,null,null,null,array['rarely used']::text[]),
('Thank you Jesus',null,null,null,null,null,null,array['rarely used']::text[]),
('This I Believe (The Creed)','Hillsong Worship',null,null,null,null,null,array['rarely used']::text[]),
('You are life',null,null,null,null,null,null,array['rarely used']::text[]),
('Yours (Glory and Praise)',null,null,null,null,null,null,array['rarely used']::text[]),
('Zeal (ST)',null,null,null,null,null,null,array['rarely used']::text[]),
('Gift Carol',null,null,null,null,null,null,array['christmas']::text[]),
('Hark Hallelujah',null,null,null,null,null,null,array['christmas']::text[]),
('O Come All Ye Faithful (His Name Shall Be)',null,null,null,null,null,null,array['christmas']::text[]);
